// Built-in skins. Ship with the app, cannot be deleted.
// Custom skins (user-added JSON) live in the backend, loaded via /api/skins.

export const DARK = {
  name: 'dark',
  label: 'Dark',
  built_in: true,
  author: 'NeepFeed',
  version: 1,
  variables: {
    '--nf-bg-primary': '#0b0d10',
    '--nf-bg-secondary': '#14171c',
    '--nf-bg-tertiary': '#1a1e25',
    '--nf-text-primary': '#e8ebef',
    '--nf-text-secondary': '#8a939f',
    '--nf-text-muted': '#5a6370',
    '--nf-accent': '#ff6b3d',
    '--nf-accent-hover': '#ff855e',
    '--nf-upvote': '#ff6b3d',
    '--nf-downvote': '#6b7280',
    '--nf-comment-color': '#8a939f',
    '--nf-nsfw-badge': '#ef4444',
    '--nf-flair-bg': 'rgba(255, 107, 61, 0.10)',
    '--nf-flair-text': '#ff6b3d',
    '--nf-border': 'rgba(255, 255, 255, 0.05)',
    '--nf-border-focus': '#ff6b3d',
    '--nf-shadow': '0 10px 15px -3px rgba(0, 0, 0, 0.3)',
    '--nf-header-bg': 'rgba(11, 13, 16, 0.75)',
    '--nf-modal-overlay': 'rgba(0, 0, 0, 0.7)',
    '--nf-modal-bg': '#14171c',
    '--nf-button-bg': '#ff6b3d',
    '--nf-button-text': '#000000',
    '--nf-button-hover': '#ff855e',
    '--nf-input-bg': '#0b0d10',
    '--nf-input-border': 'rgba(255, 255, 255, 0.10)',
    '--nf-input-focus': 'rgba(255, 107, 61, 0.40)',
    '--nf-scrollbar-thumb': '#3a4150',
    '--nf-scrollbar-track': '#0b0d10',
    '--nf-link-color': '#ff6b3d',
    '--nf-link-hover': '#ff855e',
    '--nf-video-overlay': 'rgba(0, 0, 0, 0.5)',
    '--nf-success': '#22c55e',
    '--nf-warning': '#f59e0b',
    '--nf-error': '#ef4444',
    '--nf-seen': '#3a4150',
    '--nf-font-family': '"Inter", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
    '--nf-font-size-base': '14px',
    '--nf-font-size-sm': '12px',
    '--nf-font-size-lg': '18px',
    '--nf-font-size-xl': '24px',
    '--nf-card-radius': '14px',
    '--nf-card-padding': '16px',
    '--nf-feed-max-width': '768px',
  },
};

export const LIGHT = {
  name: 'light',
  label: 'Light',
  built_in: true,
  author: 'NeepFeed',
  version: 1,
  variables: {
    '--nf-bg-primary': '#ffffff',
    '--nf-bg-secondary': '#f8fafc',
    '--nf-bg-tertiary': '#f1f5f9',
    '--nf-text-primary': '#0f172a',
    '--nf-text-secondary': '#475569',
    '--nf-text-muted': '#94a3b8',
    '--nf-accent': '#e14a1e',
    '--nf-accent-hover': '#c43f18',
    '--nf-upvote': '#e14a1e',
    '--nf-downvote': '#6b7280',
    '--nf-comment-color': '#475569',
    '--nf-nsfw-badge': '#dc2626',
    '--nf-flair-bg': 'rgba(225, 74, 30, 0.10)',
    '--nf-flair-text': '#c43f18',
    '--nf-border': '#e2e8f0',
    '--nf-border-focus': '#e14a1e',
    '--nf-shadow': '0 1px 3px rgba(15, 23, 42, 0.08)',
    '--nf-header-bg': 'rgba(255, 255, 255, 0.85)',
    '--nf-modal-overlay': 'rgba(15, 23, 42, 0.40)',
    '--nf-modal-bg': '#ffffff',
    '--nf-button-bg': '#e14a1e',
    '--nf-button-text': '#ffffff',
    '--nf-button-hover': '#c43f18',
    '--nf-input-bg': '#ffffff',
    '--nf-input-border': '#e2e8f0',
    '--nf-input-focus': 'rgba(225, 74, 30, 0.40)',
    '--nf-scrollbar-thumb': '#cbd5e1',
    '--nf-scrollbar-track': '#f1f5f9',
    '--nf-link-color': '#c43f18',
    '--nf-link-hover': '#e14a1e',
    '--nf-video-overlay': 'rgba(15, 23, 42, 0.50)',
    '--nf-success': '#16a34a',
    '--nf-warning': '#d97706',
    '--nf-error': '#dc2626',
    '--nf-seen': '#cbd5e1',
    '--nf-font-family': '"Inter", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
    '--nf-font-size-base': '14px',
    '--nf-font-size-sm': '12px',
    '--nf-font-size-lg': '18px',
    '--nf-font-size-xl': '24px',
    '--nf-card-radius': '14px',
    '--nf-card-padding': '16px',
    '--nf-feed-max-width': '768px',
  },
};

export const PAPER = {
  name: 'paper',
  label: 'Paper',
  built_in: true,
  author: 'NeepFeed',
  version: 1,
  variables: {
    '--nf-bg-primary': '#faf6f0',
    '--nf-bg-secondary': '#ffffff',
    '--nf-bg-tertiary': '#f0ebe3',
    '--nf-text-primary': '#2c2418',
    '--nf-text-secondary': '#6b5d4d',
    '--nf-text-muted': '#9c8e7e',
    '--nf-accent': '#8b4513',
    '--nf-accent-hover': '#a0522d',
    '--nf-upvote': '#cc4400',
    '--nf-downvote': '#5b4a8a',
    '--nf-comment-color': '#2e7d32',
    '--nf-nsfw-badge': '#b71c1c',
    '--nf-flair-bg': '#f0ebe3',
    '--nf-flair-text': '#8b4513',
    '--nf-border': '#d4c5b0',
    '--nf-border-focus': '#8b4513',
    '--nf-shadow': '0 1px 4px rgba(44, 36, 24, 0.08)',
    '--nf-header-bg': 'rgba(250, 246, 240, 0.88)',
    '--nf-modal-overlay': 'rgba(44, 36, 24, 0.40)',
    '--nf-modal-bg': '#ffffff',
    '--nf-button-bg': '#8b4513',
    '--nf-button-text': '#faf6f0',
    '--nf-button-hover': '#a0522d',
    '--nf-input-bg': '#ffffff',
    '--nf-input-border': '#d4c5b0',
    '--nf-input-focus': 'rgba(139, 69, 19, 0.40)',
    '--nf-scrollbar-thumb': '#d4c5b0',
    '--nf-scrollbar-track': '#faf6f0',
    '--nf-link-color': '#8b4513',
    '--nf-link-hover': '#a0522d',
    '--nf-video-overlay': 'rgba(44, 36, 24, 0.50)',
    '--nf-success': '#2e7d32',
    '--nf-warning': '#b58900',
    '--nf-error': '#b71c1c',
    '--nf-seen': '#d4c5b0',
    '--nf-font-family': '"Georgia", "Times New Roman", serif',
    '--nf-font-size-base': '15px',
    '--nf-font-size-sm': '12px',
    '--nf-font-size-lg': '19px',
    '--nf-font-size-xl': '26px',
    '--nf-card-radius': '6px',
    '--nf-card-padding': '20px',
    '--nf-feed-max-width': '720px',
  },
};

export const BUILTIN_SKINS = [DARK, LIGHT, PAPER];

export function findBuiltin(name) {
  return BUILTIN_SKINS.find((s) => s.name === name);
}
